const SETTINGS_KEY="exam-display-settings", IMAGE_KEY="exam-display-image";
const defaults={clockSize:110,imageSize:90,imagePosition:"center",showDate:true,showClock:true,clockPosition:"bottom",clockAlign:"center",clockOffset:0,clockFont:"system",dateSize:36};
const $=id=>document.getElementById(id);
let settings={...defaults},selectedFile=null,previewUrl="",sb=null;

function makeClient(){try{if(window.supabase&&typeof SUPABASE_URL!=="undefined"&&typeof SUPABASE_ANON_KEY!=="undefined")return window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY)}catch(e){console.warn("Supabase client unavailable",e)}return null}
function setAuthState(session){const signedIn=!!session;$("signInForm").hidden=signedIn;$("signOut").hidden=!signedIn;$("adminControls").hidden=!signedIn;$("authStatus").textContent=signedIn?`เข้าสู่ระบบแล้ว: ${session.user.email}`:"กรุณาเข้าสู่ระบบก่อนใช้งานหน้า Admin";$("saveSettings").disabled=!signedIn;$("publish").disabled=!signedIn}
async function signIn(){if(!sb)return setStatus("⚠️ ไม่พบการตั้งค่า Supabase");const email=$("email").value.trim(),password=$("password").value;if(!email||!password)return setStatus("⚠️ กรอกอีเมลและรหัสผ่าน");setStatus("กำลังเข้าสู่ระบบ...");const {error}=await sb.auth.signInWithPassword({email,password});if(error)return setStatus(`⚠️ เข้าสู่ระบบไม่สำเร็จ: ${error.message}`);setStatus("✅ เข้าสู่ระบบแล้ว")}
async function signOut(){if(!sb)return;const {error}=await sb.auth.signOut();setStatus(error?`⚠️ ${error.message}`:"ออกจากระบบแล้ว")}
function localSettings(){try{return {...defaults,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}")} }catch{return {...defaults}}}
function setStatus(message){$("status").textContent=message}
function saveLocal(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));if(previewUrl.startsWith("data:"))localStorage.setItem(IMAGE_KEY,previewUrl)}
function setPreviewImage(url){previewUrl=url||"";const image=$("previewImage"),empty=$("previewEmpty");if(url){image.src=url;image.hidden=false;empty.hidden=true}else{image.hidden=true;empty.hidden=false}}
function syncControls(){
  $("clockSize").value=settings.clockSize;$("imageSize").value=settings.imageSize;$("clockOffset").value=settings.clockOffset;$("clockFont").value=settings.clockFont;$("dateSize").value=settings.dateSize;$("clockValue").value=settings.clockSize;$("imageValue").value=settings.imageSize;$("clockOffsetValue").value=settings.clockOffset;$("dateSizeValue").value=settings.dateSize;
  document.querySelectorAll(".toggle").forEach(button=>{const on=!!settings[button.dataset.setting];button.classList.toggle("is-on",on);button.setAttribute("aria-pressed",on);button.querySelector("b").textContent=on?"เปิด":"ปิด"});
  document.querySelectorAll(".choice").forEach(button=>button.classList.toggle("active",settings[button.dataset.group]===button.dataset.value));
}
function renderPreview(){
  const now=new Date();$("previewDate").textContent=now.toLocaleDateString("th-TH",{weekday:"long",year:"numeric",month:"long",day:"numeric"});$("previewClock").textContent=now.toLocaleTimeString("th-TH",{hour12:false});
  const screen=$("previewScreen"),clock=$("previewClock"),date=$("previewDate"),wrap=$("previewImageWrap");
  screen.className=`preview-screen clock-${settings.clockPosition} clock-align-${settings.clockAlign}`;clock.style.fontSize=`${Math.max(18,settings.clockSize*.25)}px`;clock.style.transform=`translateY(${settings.clockOffset*.25}px)`;clock.style.fontFamily=fontFamily(settings.clockFont);date.style.fontSize=`${Math.max(9,settings.dateSize*.25)}px`;clock.hidden=!settings.showClock;date.hidden=!settings.showDate;wrap.style.alignItems={top:"flex-start",center:"center",bottom:"flex-end"}[settings.imagePosition];$("previewImage").style.maxWidth=`${settings.imageSize}%`;
}
function fontFamily(font){return {serif:'Georgia,"Times New Roman",serif',mono:'Consolas,"Courier New",monospace',thai:'"Noto Sans Thai",Tahoma,Arial,sans-serif'}[font]||'Arial,"Noto Sans Thai",sans-serif'}
function readSettingsRow(row){if(!row)return;settings={...settings,clockSize:row.clock_size??settings.clockSize,imageSize:row.image_size??settings.imageSize,imagePosition:row.image_position??settings.imagePosition,showDate:row.show_date??settings.showDate,showClock:row.show_clock??settings.showClock,clockPosition:row.clock_position??settings.clockPosition,clockAlign:row.clock_align??row.clock_alignment??settings.clockAlign,clockOffset:row.clock_offset??settings.clockOffset,clockFont:row.clock_font??settings.clockFont,dateSize:row.date_size??settings.dateSize};if(row.image_url)setPreviewImage(row.image_url)}
async function load(){settings=localSettings();setPreviewImage(localStorage.getItem(IMAGE_KEY)||"");sb=makeClient();setAuthState(null);if(sb){const {data:{session}}=await sb.auth.getSession();setAuthState(session);sb.auth.onAuthStateChange((_event,session)=>setAuthState(session));try{const {data,error}=await sb.from("display_settings").select("*").eq("id",1).maybeSingle();if(error)console.warn(error.message);else readSettingsRow(data)}catch(e){console.warn(e)}}syncControls();renderPreview()}
async function saveSettings(){saveLocal();if(!sb){setStatus("✅ บันทึกในเบราว์เซอร์แล้ว");return true}try{const row={id:1,clock_size:settings.clockSize,image_size:settings.imageSize,image_position:settings.imagePosition,show_date:settings.showDate,show_clock:settings.showClock,clock_position:settings.clockPosition,clock_align:settings.clockAlign,clock_offset:settings.clockOffset,clock_font:settings.clockFont,date_size:settings.dateSize};let {error}=await sb.from("display_settings").upsert(row);if(error&&/clock_align/i.test(error.message)){delete row.clock_align;error=(await sb.from("display_settings").upsert(row)).error}if(error)throw error;setStatus("✅ บันทึกการตั้งค่าแล้ว");return true}catch(e){setStatus(`⚠️ บันทึกเฉพาะเครื่อง: ${e.message||"เชื่อมต่อ Supabase ไม่ได้"}`);return false}}
async function publish(){await saveSettings();if(!selectedFile){setStatus("✅ เผยแพร่การตั้งค่าแล้ว");return}if(!sb){saveLocal();setStatus("✅ บันทึกรูปในเบราว์เซอร์แล้ว");return}try{setStatus("กำลังอัปโหลดรูป...");const ext=(selectedFile.name.split(".").pop()||"jpg").toLowerCase(),path=`display-${Date.now()}.${ext}`;const {error}=await sb.storage.from(STORAGE_BUCKET).upload(path,selectedFile,{contentType:selectedFile.type,upsert:false});if(error)throw error;const {data}=sb.storage.from(STORAGE_BUCKET).getPublicUrl(path);const {error:dbError}=await sb.from("display_settings").upsert({id:1,image_url:data.publicUrl});if(dbError)throw dbError;setPreviewImage(data.publicUrl);setStatus("✅ อัปโหลดและเผยแพร่แล้ว")}catch(e){setStatus(`⚠️ เก็บรูปไว้ในเครื่องแล้ว: ${e.message||"อัปโหลดไม่สำเร็จ"}`);saveLocal()}}

document.querySelectorAll(".toggle").forEach(button=>button.onclick=()=>{settings[button.dataset.setting]=!settings[button.dataset.setting];syncControls();renderPreview()});
document.querySelectorAll(".choice").forEach(button=>button.onclick=()=>{settings[button.dataset.group]=button.dataset.value;syncControls();renderPreview()});
$("clockSize").oninput=e=>{settings.clockSize=+e.target.value;syncControls();renderPreview()};$("imageSize").oninput=e=>{settings.imageSize=+e.target.value;syncControls();renderPreview()};$("clockOffset").oninput=e=>{settings.clockOffset=+e.target.value;syncControls();renderPreview()};$("dateSize").oninput=e=>{settings.dateSize=+e.target.value;syncControls();renderPreview()};$("clockFont").onchange=e=>{settings.clockFont=e.target.value;renderPreview()};
$("imageFile").onchange=e=>{selectedFile=e.target.files[0]||null;if(!selectedFile)return;const reader=new FileReader();reader.onload=()=>{setPreviewImage(reader.result);renderPreview()};reader.readAsDataURL(selectedFile)};
$("signIn").onclick=signIn;$("signOut").onclick=signOut;$("saveSettings").onclick=saveSettings;$("publish").onclick=publish;setInterval(renderPreview,1000);load();
