const SETTINGS_KEY="exam-display-settings", IMAGE_KEY="exam-display-image";
const defaults={clockSize:110,imageSize:90,imagePosition:"center",showDate:true,showClock:true,clockPosition:"bottom",clockAlign:"center",clockOffset:0,clockFont:"system",dateSize:36};
let settings={...defaults},sb=null;
function getLocal(){try{return {...defaults,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}")} }catch{return {...defaults}}}
function makeClient(){try{return window.supabase&&typeof SUPABASE_URL!=="undefined"&&typeof SUPABASE_ANON_KEY!=="undefined"?window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null}catch{return null}}
function fontFamily(font){return {serif:'Georgia,"Times New Roman",serif',mono:'Consolas,"Courier New",monospace',thai:'"Noto Sans Thai",Tahoma,Arial,sans-serif'}[font]||'Arial,"Noto Sans Thai",sans-serif'}
function apply(){const s=settings,wrap=document.querySelector(".image-wrap"),clock=document.getElementById("clock"),date=document.getElementById("dateText");document.documentElement.style.setProperty("--clock-size",s.clockSize+"px");document.documentElement.style.setProperty("--image-size",s.imageSize+"%");wrap.style.alignItems={top:"flex-start",center:"center",bottom:"flex-end"}[s.imagePosition]||"center";clock.style.display=s.showClock?"flex":"none";clock.style.transform=`translateY(${s.clockOffset}px)`;clock.style.fontFamily=fontFamily(s.clockFont);date.style.fontSize=`${s.dateSize}px`;date.parentElement.style.display=s.showDate?"flex":"none";document.getElementById("display").className=`display clock-${s.clockPosition} clock-align-${s.clockAlign}`}
function update(){const now=new Date();document.getElementById("clock").textContent=now.toLocaleTimeString("th-TH",{hour12:false});document.getElementById("dateText").textContent=now.toLocaleDateString("th-TH",{weekday:"long",year:"numeric",month:"long",day:"numeric"})}
function image(url){const img=document.getElementById("examImage"),empty=document.getElementById("empty");if(url){img.src=url;img.hidden=false;empty.hidden=true}else{img.hidden=true;empty.hidden=false}}
function useRow(row){if(!row)return;settings={...settings,clockSize:row.clock_size??settings.clockSize,imageSize:row.image_size??settings.imageSize,imagePosition:row.image_position??settings.imagePosition,showDate:row.show_date??settings.showDate,showClock:row.show_clock??settings.showClock,clockPosition:row.clock_position??settings.clockPosition,clockAlign:row.clock_align??row.clock_alignment??settings.clockAlign,clockOffset:row.clock_offset??settings.clockOffset,clockFont:row.clock_font??settings.clockFont,dateSize:row.date_size??settings.dateSize};if(row.image_url)image(row.image_url);apply()}
async function loadRemote(){sb=makeClient();if(!sb)return;try{const {data,error}=await sb.from("display_settings").select("*").eq("id",1).maybeSingle();if(!error)useRow(data);sb.channel("exam-display-settings").on("postgres_changes",{event:"*",schema:"public",table:"display_settings"},payload=>useRow(payload.new)).subscribe()}catch(e){console.warn("Supabase unavailable; using this browser's saved version",e)}}
function loadSupabaseLibrary(){if(window.supabase)return Promise.resolve();return new Promise(resolve=>{const script=document.createElement("script");script.src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";script.onload=resolve;script.onerror=resolve;document.head.append(script)})}
function fullscreen(){const target=document.documentElement;if(document.fullscreenElement)document.exitFullscreen();else target.requestFullscreen?.().catch(()=>{})}
function addFullscreenButton(){const button=document.createElement("button");button.type="button";button.className="fullscreen-btn";button.textContent="⛶ เต็มหน้าจอ";button.setAttribute("aria-label","เปิดหรือปิดเต็มหน้าจอ");button.onclick=fullscreen;document.getElementById("display").append(button)}
settings=getLocal();image(localStorage.getItem(IMAGE_KEY));apply();update();addFullscreenButton();setInterval(update,1000);loadSupabaseLibrary().then(loadRemote);
