const SETTINGS_KEY="exam-display-settings", IMAGE_KEY="exam-display-image", THEME_KEY="exam-display-theme";
const defaults={clockSize:110,imageSize:90,imagePosition:"center",showDate:true,showClock:true,clockPosition:"bottom",clockAlign:"center",clockOffset:0,clockFont:"system",dateSize:36,dateOffset:0,slideshowSeconds:8,theme:"midnight"};
let settings={...defaults},sb=null,schedules=[],slideIndex=0,slideTimer=null,fallbackUrl="";
function getLocal(){try{return {...defaults,...JSON.parse(localStorage.getItem(SETTINGS_KEY)||"{}")} }catch{return {...defaults}}}
function makeClient(){try{return window.supabase&&typeof SUPABASE_URL!=="undefined"&&typeof SUPABASE_ANON_KEY!=="undefined"?window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null}catch{return null}}
function fontFamily(font){return {serif:'Georgia,"Times New Roman",serif',mono:'Consolas,"Courier New",monospace',thai:'"Noto Sans Thai",Tahoma,Arial,sans-serif'}[font]||'Arial,"Noto Sans Thai",sans-serif'}
function apply(){const s=settings,wrap=document.querySelector(".image-wrap"),clock=document.getElementById("clock"),date=document.getElementById("dateText");document.documentElement.style.setProperty("--clock-size",s.clockSize+"px");document.documentElement.style.setProperty("--image-size",s.imageSize+"%");wrap.style.alignItems={top:"flex-start",center:"center",bottom:"flex-end"}[s.imagePosition]||"center";clock.style.display=s.showClock?"flex":"none";clock.style.transform=`translateY(${s.clockOffset}px)`;clock.style.fontFamily=fontFamily(s.clockFont);date.style.fontSize=`${s.dateSize}px`;date.style.transform=`translateY(${s.dateOffset||0}px)`;date.parentElement.style.display=s.showDate?"flex":"none";document.getElementById("display").className=`display clock-${s.clockPosition} clock-align-${s.clockAlign}`}
function update(){const now=new Date();document.getElementById("clock").textContent=now.toLocaleTimeString("th-TH",{hour12:false});document.getElementById("dateText").textContent=now.toLocaleDateString("th-TH",{weekday:"long",year:"numeric",month:"long",day:"numeric"})}
function image(url){const img=document.getElementById("examImage"),empty=document.getElementById("empty");if(url){img.src=url;img.hidden=false;empty.hidden=true}else{img.hidden=true;empty.hidden=false}}
function setTheme(theme){const light=theme==="light";document.getElementById("display").classList.toggle("display-light",light);const button=document.getElementById("themeToggle");button.setAttribute("aria-pressed",light);button.textContent=light?"🌙 โหมดมืด":"☀️ โหมดสว่าง";localStorage.setItem(THEME_KEY,light?"light":"dark")}
function activeSchedules(){const now=new Date();return schedules.filter(row=>(!row.start_at||new Date(row.start_at)<=now)&&(!row.end_at||new Date(row.end_at)>=now)).sort((a,b)=>(a.sort_order??0)-(b.sort_order??0))}
function renderSlide(){const active=activeSchedules();if(active.length){slideIndex=((slideIndex%active.length)+active.length)%active.length;image(active[slideIndex].image_url)}else{image(fallbackUrl||"")}}
function restartSlideshow(){if(slideTimer)clearInterval(slideTimer);slideIndex=0;renderSlide();const active=activeSchedules();if(active.length>1){const seconds=Math.max(3,settings.slideshowSeconds||8);slideTimer=setInterval(()=>{slideIndex++;renderSlide()},seconds*1000)}}
function useRow(row){if(!row)return;settings={...settings,clockSize:row.clock_size??settings.clockSize,imageSize:row.image_size??settings.imageSize,imagePosition:row.image_position??settings.imagePosition,showDate:row.show_date??settings.showDate,showClock:row.show_clock??settings.showClock,clockPosition:row.clock_position??settings.clockPosition,clockAlign:row.clock_align??row.clock_alignment??settings.clockAlign,clockOffset:row.clock_offset??settings.clockOffset,clockFont:row.clock_font??settings.clockFont,dateSize:row.date_size??settings.dateSize,dateOffset:row.date_offset??settings.dateOffset,slideshowSeconds:row.slideshow_seconds??settings.slideshowSeconds};if(row.image_url)fallbackUrl=row.image_url;apply();restartSlideshow()}
async function loadRemote(){sb=makeClient();if(!sb)return;try{const {data,error}=await sb.from("display_settings").select("*").eq("id",1).maybeSingle();if(!error)useRow(data);const {data:rows,error:schedErr}=await sb.from("exam_schedules").select("*").order("sort_order",{ascending:true});if(!schedErr&&rows){schedules=rows;restartSlideshow()}sb.channel("exam-display-settings").on("postgres_changes",{event:"*",schema:"public",table:"display_settings"},payload=>useRow(payload.new)).subscribe();sb.channel("exam-display-schedules").on("postgres_changes",{event:"*",schema:"public",table:"exam_schedules"},async()=>{const {data:rows2}=await sb.from("exam_schedules").select("*").order("sort_order",{ascending:true});schedules=rows2||[];restartSlideshow()}).subscribe()}catch(e){console.warn("Supabase unavailable; using this browser's saved version",e)}}
function loadSupabaseLibrary(){if(window.supabase)return Promise.resolve();return new Promise(resolve=>{const script=document.createElement("script");script.src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";script.onload=resolve;script.onerror=resolve;document.head.append(script)})}
function fullscreen(){const target=document.documentElement;if(document.fullscreenElement)document.exitFullscreen();else target.requestFullscreen?.().catch(()=>{})}
function addFullscreenButton(){const button=document.createElement("button");button.type="button";button.className="fullscreen-btn";button.textContent="⛶ เต็มหน้าจอ";button.setAttribute("aria-label","เปิดหรือปิดเต็มหน้าจอ");button.onclick=fullscreen;document.getElementById("display").append(button)}
settings=getLocal();fallbackUrl=localStorage.getItem(IMAGE_KEY)||"";image(fallbackUrl);setTheme(localStorage.getItem(THEME_KEY)||"dark");document.getElementById("themeToggle").onclick=()=>setTheme(document.getElementById("display").classList.contains("display-light")?"dark":"light");apply();update();addFullscreenButton();setInterval(update,1000);loadSupabaseLibrary().then(loadRemote);
