-- Existing installations: run schema.sql instead. It is safe to run repeatedly
-- and includes the current display-setting columns, RLS policies, Realtime,
-- and the public exam-images bucket setup.
